name: Deploy staging branch on remote host

on:
  workflow_dispatch:
  push:
    branches:
      - staging

concurrency:
  group: deploy-staging

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      host: fr-int-wpupdate.hostinger.io
      path: /var/www/html/staging
